import type { SiteMeta } from '@/lib/types';

import { artist } from './artist';

export const site: SiteMeta = {
  title: `${artist.name} — ${artist.title}`,
  description: artist.bioShort,
  url: 'https://borshon.lorapok.tech',
};

export const navigation = [
  { label: 'Work', href: '/work' },
  { label: 'About', href: '/about' },
  { label: 'CV', href: '/cv' },
  { label: 'Contact', href: '/contact' },
];

// Generated by `npm run pdfs` into public/documents/.
export const documents = [
  {
    label: 'Portfolio',
    href: '/documents/portfolio.pdf',
    note: 'Full case studies, A4 landscape',
  },
  { label: 'CV', href: '/documents/cv.pdf', note: 'Single page, A4' },
  {
    label: 'Project proposal',
    href: '/documents/proposal.pdf',
    note: 'The Frozen Liquidity, A4',
  },
];
